# This is a pipeline for the AI4Devs project
name: AI4Devs Pipeline

on:
  push:
    branches:
      - 'jiba21:JIBA-Pipeline'
      
  pull_request:
    branches: 
      - 'main'
    types: [synchronize, opened, reopened, ready_for_review]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-tests-build.yml
