name: AI4Devs Pipeline - Backend Deploy

on:
  push:
    branches:
      - pipeline-larivasd

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Run Prisma generate
      working-directory: ./backend
      run: npx prisma generate
      
    - name: Run tests
      working-directory: ./backend
      run: npm test
      env:
        NODE_ENV: test
        
    - name: Build application
      working-directory: ./backend
      run: npm run build
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
        SOURCE: "backend/"
