name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:  # Added this line to define an additional trigger
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
            echo "Installing dependencies"
            cd backend
            npm install

      - name: Run backend tests
        run: |
            echo "Running backend tests"
            cd backend
            npm test

      - name: Build backend
        run: |
            echo "Building backend"
            cd backend
            npm run build

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "Deploying to EC2"
          chmod 600 $EC2_KEY
          scp -i $EC2_KEY -o StrictHostKeyChecking=no -r ./backend/dist/* $EC2_USER@$EC2_HOST:/opt/backend
          ssh -i $EC2_KEY -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "cd /opt/backend && npm install --production && pm2 restart all"